### ISSUE TITLE
This is awsome. Do you need any help?

### ISSUE THREAD

**Issue by catskul** [LinusCDE/rmWacomToMouse#3]
I'd love to keep this project alive and healthy. Do you need any help with any tasks?

**Comment by LinusCDE** [comment]
Hi.
Again, thank you for your kind question.

This answer has the same gist as my answer on [the other issue](https://github.com/LinusCDE/rmTabletDriver/issues/2).

Things that could be done here are:

- UI for selecting a custom area for the mouse.
- TCP -> UDP.

Things as in the other issue apply here, too.

Again, if you want, I can add you directly as an contributor.
